const $ = s => document.querySelector(s);
const LOCAL_KEY='omniplay-workspace-v2';
const state={categories:[],activeCategoryId:null,activePageId:null};
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const activeCategory=()=>state.categories.find(c=>c.id===state.activeCategoryId);
const activePage=()=>activeCategory()?.pages?.find(p=>p.id===state.activePageId);
const typeIcon=t=>({sheet:'📊',files:'📄',photos:'🖼️',videos:'🎬'})[t]||'📄';
function load(){try{state.categories=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch{state.categories=[]} $('#cloudStatus').textContent='🧪 測試模式・本機儲存';renderNav();renderPage()}
function save(){localStorage.setItem(LOCAL_KEY,JSON.stringify(state.categories));$('#cloudStatus').textContent='✓ 已自動儲存到此瀏覽器'}
function renderNav(){const root=$('#categoryList');root.innerHTML='';state.categories.forEach(cat=>{const box=document.createElement('div');box.className='category';box.innerHTML=`<div class="category-head ${cat.id===state.activeCategoryId?'active':''}"><span>📁 ${esc(cat.name)}</span><button class="mini" title="刪除分類">⋯</button></div><div class="category-pages"></div>`;box.querySelector('.category-head').onclick=e=>{if(e.target.classList.contains('mini'))return;state.activeCategoryId=cat.id;state.activePageId=cat.pages?.[0]?.id||null;renderNav();renderPage()};box.querySelector('.mini').onclick=()=>{if(confirm(`刪除分類「${cat.name}」以及裡面的所有頁面？`)){state.categories=state.categories.filter(x=>x.id!==cat.id);state.activeCategoryId=null;state.activePageId=null;save();renderNav();renderPage()}};const pages=box.querySelector('.category-pages');(cat.pages||[]).forEach(p=>{const row=document.createElement('div');row.className=`page-row ${p.id===state.activePageId?'active':''}`;row.innerHTML=`<button class="page-link">${typeIcon(p.type)} ${esc(p.name)}</button><button class="page-delete" title="刪除">×</button>`;row.querySelector('.page-link').onclick=()=>{state.activeCategoryId=cat.id;state.activePageId=p.id;renderNav();renderPage()};row.querySelector('.page-delete').onclick=()=>{if(confirm(`刪除頁面「${p.name}」？`)){cat.pages=cat.pages.filter(x=>x.id!==p.id);state.activePageId=cat.pages[0]?.id||null;save();renderNav();renderPage()}};pages.appendChild(row)});root.appendChild(box)});$('#addPageBtn').disabled=!state.activeCategoryId}
function renderPage(){const page=activePage(),cat=activeCategory();$('#emptyState').classList.toggle('hidden',!!page||!!cat);$('#workspace').classList.toggle('hidden',!page);$('#breadcrumb').textContent=cat?`工作區 / ${cat.name}`:'工作區';$('#pageTitle').textContent=page?page.name:(cat?cat.name:'歡迎使用 OMNIPLAY');if(!page){if(cat)$('#emptyState').innerHTML='<div><h2>這個分類還沒有頁面</h2><p>按右上角「新增頁面」開始。</p></div>';return}page.type==='sheet'?renderSheet(page):renderFiles(page)}
function colName(n){let s='';for(n++;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function renderSheet(page){page.sheet||={rows:50,cols:15,cells:{}};const ws=$('#workspace');ws.innerHTML=`<div class="toolbar"><button id="undoBtn">↶ 復原</button><button id="addRowBtn">＋10 列</button><button id="addColBtn">＋5 欄</button><button id="importCsvBtn">匯入 CSV</button><button id="exportCsvBtn">匯出 CSV</button><button id="clearSheetBtn">清空</button></div><div class="formula-bar"><input id="cellAddress" value="A1" readonly><input id="formulaInput" placeholder="內容或公式：=SUM(A1:A5)"></div><div class="sheet-wrap"><table id="sheet" class="sheet"></table></div>`;const table=$('#sheet');let selected='A1',history=[];function build(){let h='<thead><tr><th class="row-head"></th>';for(let c=0;c<page.sheet.cols;c++)h+=`<th>${colName(c)}</th>`;h+='</tr></thead><tbody>';for(let r=1;r<=page.sheet.rows;r++){h+=`<tr><th class="row-head">${r}</th>`;for(let c=0;c<page.sheet.cols;c++){const a=`${colName(c)}${r}`,raw=page.sheet.cells[a]??'';h+=`<td contenteditable="true" data-a="${a}">${esc(displayValue(raw,page.sheet.cells))}</td>`}h+='</tr>'}table.innerHTML=h+'</tbody>';table.querySelectorAll('td').forEach(td=>{td.onfocus=()=>{selected=td.dataset.a;$('#cellAddress').value=selected;$('#formulaInput').value=page.sheet.cells[selected]??''};td.onblur=()=>{const old=page.sheet.cells[td.dataset.a]??'',val=td.textContent;if(old!==val){history.push(JSON.stringify(page.sheet.cells));page.sheet.cells[td.dataset.a]=val;save();build()}};td.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();td.blur()}}})}$('#formulaInput').onkeydown=e=>{if(e.key==='Enter'){history.push(JSON.stringify(page.sheet.cells));page.sheet.cells[selected]=e.target.value;save();build()}};$('#undoBtn').onclick=()=>{const p=history.pop();if(p){page.sheet.cells=JSON.parse(p);save();build()}};$('#addRowBtn').onclick=()=>{page.sheet.rows+=10;save();build()};$('#addColBtn').onclick=()=>{page.sheet.cols+=5;save();build()};$('#clearSheetBtn').onclick=()=>{if(confirm('確定清空？')){page.sheet.cells={};save();build()}};$('#importCsvBtn').onclick=()=>$('#csvImport').click();$('#csvImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;const rows=parseCSV(await f.text());rows.forEach((row,r)=>row.forEach((v,c)=>page.sheet.cells[`${colName(c)}${r+1}`]=v));page.sheet.rows=Math.max(page.sheet.rows,rows.length+5);page.sheet.cols=Math.max(page.sheet.cols,Math.max(...rows.map(x=>x.length),0)+2);save();build();e.target.value=''};$('#exportCsvBtn').onclick=()=>{const lines=[];for(let r=1;r<=page.sheet.rows;r++){const row=[];for(let c=0;c<page.sheet.cols;c++){const v=page.sheet.cells[`${colName(c)}${r}`]??'';row.push(`"${String(v).replaceAll('"','""')}"`)}lines.push(row.join(','))}download(`${page.name}.csv`,lines.join('\n'),'text/csv;charset=utf-8')};build()}
function displayValue(raw,cells){if(typeof raw!=='string'||!raw.startsWith('='))return raw;try{const expr=raw.slice(1).toUpperCase(),rangeVals=r=>{const m=r.match(/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/);if(!m)return[];const cn=s=>[...s].reduce((n,ch)=>n*26+ch.charCodeAt(0)-64,0)-1,v=[];for(let y=+m[2];y<=+m[4];y++)for(let x=cn(m[1]);x<=cn(m[3]);x++){const n=Number(cells[`${colName(x)}${y}`]);v.push(Number.isFinite(n)?n:0)}return v},fn=expr.match(/^(SUM|AVERAGE|AVG|MIN|MAX|COUNT)\(([^)]+)\)$/);if(fn){const v=rangeVals(fn[2]);if(fn[1]==='SUM')return v.reduce((a,b)=>a+b,0);if(fn[1]==='AVERAGE'||fn[1]==='AVG')return v.length?v.reduce((a,b)=>a+b,0)/v.length:0;if(fn[1]==='MIN')return Math.min(...v);if(fn[1]==='MAX')return Math.max(...v);if(fn[1]==='COUNT')return v.length}const safe=expr.replace(/([A-Z]+\d+)/g,m=>Number(cells[m])||0);if(!/^[0-9+\-*/().\s]+$/.test(safe))return'#ERROR!';return Function(`"use strict";return (${safe})`)()}catch{return'#ERROR!'}}
function parseCSV(text){return text.trim().split(/\r?\n/).map(line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out})}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderFiles(page){page.files||=[];const title=page.type==='photos'?'照片':page.type==='videos'?'影片':'檔案 / PDF',ws=$('#workspace');ws.innerHTML=`<div class="notice">🧪 測試版：檔案只保留在目前瀏覽器，重新選檔後可預覽；之後再接雲端 Storage。</div><div class="file-panel"><div id="uploadZone" class="upload-zone"><strong>＋ 加入${title}</strong><div class="file-meta">目前用本機測試，不會上傳到網路</div></div><div id="fileGrid" class="file-grid"></div></div>`;const input=$('#hiddenUpload');input.accept=page.type==='photos'?'image/*':page.type==='videos'?'video/*':'.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,application/pdf';$('#uploadZone').onclick=()=>input.click();input.onchange=e=>{[...e.target.files].forEach(file=>{if(page.type==='photos'&&!file.type.startsWith('image/'))return;if(page.type==='videos'&&!file.type.startsWith('video/'))return;page.files.push({id:uid('file'),name:file.name,type:file.type,size:file.size,local:true})});save();renderFiles(page);e.target.value=''};const grid=$('#fileGrid');if(!page.files.length)grid.innerHTML='<div class="file-meta">目前沒有檔案。</div>';page.files.forEach(f=>{const card=document.createElement('div');card.className='file-card';card.innerHTML=`<div class="file-placeholder">${f.type?.startsWith('image/')?'🖼️':f.type?.startsWith('video/')?'🎬':'📄'}</div><div class="file-name">${esc(f.name)}</div><div class="file-meta">${formatBytes(f.size||0)}・本機測試項目</div><button class="remove-file">刪除</button>`;card.querySelector('.remove-file').onclick=()=>{page.files=page.files.filter(x=>x.id!==f.id);save();renderFiles(page)};grid.appendChild(card)})}
function formatBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`}
$('#addCategoryBtn').onclick=()=>{$('#categoryName').value='';$('#categoryDialog').showModal()};$('#categoryForm').onsubmit=e=>{e.preventDefault();const name=$('#categoryName').value.trim();if(!name)return;const cat={id:uid('cat'),name,pages:[]};state.categories.push(cat);state.activeCategoryId=cat.id;state.activePageId=null;save();$('#categoryDialog').close();renderNav();renderPage()};$('#addPageBtn').onclick=()=>{$('#pageName').value='';$('#pageDialog').showModal()};$('#pageForm').onsubmit=e=>{e.preventDefault();const cat=activeCategory(),name=$('#pageName').value.trim(),type=$('#pageType').value;if(!cat||!name)return;const page={id:uid('page'),name,type,createdAt:new Date().toISOString()};if(type==='sheet')page.sheet={rows:50,cols:15,cells:{}};else page.files=[];cat.pages.push(page);state.activePageId=page.id;save();$('#pageDialog').close();renderNav();renderPage()};load();