import{getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import{getFirestore,collection,addDoc,getDocs,query,orderBy,limit,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import{getAuth,signInWithEmailAndPassword,signOut,setPersistence,browserLocalPersistence,browserSessionPersistence}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
const cfg={apiKey:'AIzaSyB02CLJIYLJgQ2LkMVgYomObyl1kQC84eI',authDomain:'omniplay-op.firebaseapp.com',projectId:'omniplay-op',storageBucket:'omniplay-op.firebasestorage.app',messagingSenderId:'742295844045',appId:'1:742295844045:web:8399ae7bdb21c6a9d12584'};
const SESSION_KEY='omniplay-login-session-v1',CUSTOMER_KEY='omniplay-customer-session',ADMIN_KEY='omniplay-admin-session';
const ADMIN_UID='xqDN3vaLfufEkz4TZ1omSmGkQ2A2';
const ADMIN_USERNAME='Cia_Cia';
const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function passwordHash(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function workspaceRef(){const app=getApps().length?getApps()[0]:initializeApp(cfg),db=getFirestore(app);return doc(db,'omniplay','workspace')}
function auditRef(){const app=getApps().length?getApps()[0]:initializeApp(cfg);return collection(getFirestore(app),'omniplay-audit-events')}
function canViewAudit(session=window.__omniplaySession){return!!session&&(session.superAdmin||String(session.username||'').trim().toLowerCase()==='k')}
async function recordAudit(account,action,item=''){try{await addDoc(auditRef(),{username:account.username||'',name:account.name||account.username||'',groupName:account.groupName||'',action,item:String(item||''),createdAt:serverTimestamp(),createdAtIso:new Date().toISOString()})}catch(error){console.warn('audit log',error)}}
function auditTime(value){const date=value?.toDate?.()||new Date(value||0);return Number.isNaN(date.getTime())?'—':date.toLocaleString('zh-TW',{hour12:false})}
async function showAuditLog(){let dialog=document.querySelector('#auditLogDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='auditLogDialog';dialog.style.cssText='width:min(900px,calc(100vw - 32px));max-height:82vh;border:1px solid #cbd5e1;border-radius:14px;padding:0;box-shadow:0 24px 70px rgba(15,23,42,.3)';dialog.innerHTML='<section style="padding:20px;background:#fff;color:#172033"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px"><div><h2 style="margin:0 0 4px">登入／下載紀錄</h2><small style="color:#64748b">最多顯示最近 500 筆</small></div><div style="display:flex;gap:8px"><button type="button" id="auditExport" class="secondary">下載 CSV</button><button type="button" data-audit-close class="secondary">關閉</button></div></div><div id="auditLogBody" style="overflow:auto;max-height:62vh">載入中…</div></section>';document.body.append(dialog);dialog.querySelector('[data-audit-close]').onclick=()=>dialog.close()}const body=dialog.querySelector('#auditLogBody');body.textContent='載入中…';dialog.showModal();try{const snap=await getDocs(query(auditRef(),orderBy('createdAt','desc'),limit(500))),rows=snap.docs.map(item=>item.data()).filter(row=>!(row.action==='download' && String(row.item||'').includes('登入／下載紀錄')));dialog._auditRows=rows;body.innerHTML=rows.length?'<table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr><th>時間</th><th>人員</th><th>帳號</th><th>群組</th><th>動作</th><th>項目</th></tr></thead><tbody>'+rows.map(row=>`<tr><td>${esc(auditTime(row.createdAt||row.createdAtIso))}</td><td>${esc(row.name||'—')}</td><td>${esc(row.username||'—')}</td><td>${esc(row.groupName||'—')}</td><td>${row.action==='login'?'登入':'下載'}</td><td>${esc(row.item||'—')}</td></tr>`).join('')+'</tbody></table>':'尚無紀錄';body.querySelectorAll('th,td').forEach(cell=>cell.style.cssText='padding:9px 10px;border-bottom:1px solid #e2e8f0;text-align:left;white-space:nowrap')}catch(error){console.error(error);body.textContent='紀錄載入失敗'}dialog.querySelector('#auditExport').onclick=()=>{const rows=dialog._auditRows||[],csv=[['時間','人員','帳號','群組','動作','項目'],...rows.map(row=>[auditTime(row.createdAt||row.createdAtIso),row.name,row.username,row.groupName,row.action==='login'?'登入':'下載',row.item])].map(cols=>cols.map(value=>'"'+String(value||'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`OMNIPLAY登入下載紀錄_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}}
function installDownloadAudit(session){document.addEventListener('click',event=>{const target=event.target.closest?.('a[download],button,[role="button"]');if(!target||target.closest('#auditLogDialog')||target.closest('.audit-log-btn'))return;const label=(target.getAttribute('download')||target.title||target.getAttribute('aria-label')||target.textContent||'').trim();if(/下載|download/i.test(label))recordAudit(session,'download',label.slice(0,180))},true)}
function readSession(){for(const store of[localStorage,sessionStorage]){try{const value=JSON.parse(store.getItem(SESSION_KEY)||'null');if(value?.authUid===ADMIN_UID)return value}catch{}}return null}
function saveSession(session,remember){for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}const store=remember?localStorage:sessionStorage;store.setItem(SESSION_KEY,JSON.stringify(session));if(session.internal)store.setItem(ADMIN_KEY,JSON.stringify(session));else store.setItem(CUSTOMER_KEY,JSON.stringify(session))}
async function logout(){for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}await signOut(getAuth());location.reload()}
function addLogout(session){if(document.querySelector('.session-controls'))return;const controls=document.createElement('div');controls.className='session-controls';const name=document.createElement('span');name.className='login-user';name.textContent=session.name||session.username;const logoutButton=document.createElement('button');logoutButton.type='button';logoutButton.className='secondary logout-btn';logoutButton.textContent='登出';logoutButton.onclick=logout;controls.append(name);if(canViewAudit(session)){const auditButton=document.createElement('button');auditButton.type='button';auditButton.className='secondary audit-log-btn';auditButton.textContent='登入／下載紀錄';auditButton.onclick=showAuditLog;controls.append(auditButton)}controls.append(logoutButton);document.body.append(controls)}
function installReadOnlyMode(){window.__omniplayCanEdit=false;document.documentElement.classList.add('viewer-mode');const style=document.createElement('style');style.textContent='.viewer-mode .admin-only,.viewer-mode .platform-actions,.viewer-mode .group-manager-actions,.viewer-mode #addCategory,.viewer-mode #addPage,.viewer-mode [data-edit-action]{display:none!important}.viewer-mode [contenteditable="true"]{cursor:default!important}.viewer-mode .sheet-workspace button:not(#glNativeSearch button){pointer-events:none!important;opacity:.55}.viewer-mode #glNativeSearch button{pointer-events:auto!important;opacity:1!important}';document.head.appendChild(style);const safe=target=>!!target?.closest?.('.session-controls,#glNativeSearch,.theme-switch,[data-viewer-control]'),lockFields=()=>document.querySelectorAll('#workspace input,#workspace textarea,#workspace select,[contenteditable="true"]').forEach(el=>{if(safe(el))return;if(el.matches('[contenteditable]'))el.contentEditable='false';else el.disabled=true});new MutationObserver(lockFields).observe(document.documentElement,{childList:true,subtree:true});lockFields();for(const type of['beforeinput','paste','cut','drop'])document.addEventListener(type,e=>{if(!safe(e.target))e.preventDefault()},true);document.addEventListener('contextmenu',e=>{if(e.target.closest?.('#workspace')&&!safe(e.target)){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('keydown',e=>{if(safe(e.target))return;const sheet=e.target.closest?.('.sheet-workspace')||document.querySelector('.sheet-workspace:hover');if(!sheet)return;const blocked=e.key.length===1&&!e.ctrlKey&&!e.metaKey||['Backspace','Delete','Enter','F2'].includes(e.key)||(e.ctrlKey||e.metaKey)&&['v','x'].includes(e.key.toLowerCase());if(blocked){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('click',e=>{if(safe(e.target))return;const button=e.target.closest?.('button,[role="button"]');if(!button)return;const label=`${button.textContent||''} ${button.title||''} ${button.getAttribute('aria-label')||''}`;if(button.closest('.sheet-workspace')||/(新增|建立|編輯|修改|刪除|移除|儲存|上傳|設定權限)/.test(label)){e.preventDefault();e.stopImmediatePropagation()}},true)}
function loginMarkup(){return`<main class="login-screen"><section class="login-card"><div class="login-brand"><span>🔥</span><div><strong>OMNIPLAY OP</strong><small>Workspace Management</small></div></div><div class="login-heading"><h1>登入工作區</h1><p>請輸入管理員提供的帳號與密碼</p></div><form id="loginForm"><label>管理員電子郵件<input id="loginUsername" type="email" autocomplete="username" required placeholder="請輸入 Firebase 管理員電子郵件"></label><label>登入密碼<div class="login-password"><input id="loginPassword" type="password" autocomplete="current-password" required placeholder="請輸入密碼"><button type="button" id="togglePassword" aria-label="顯示密碼">顯示</button></div></label><div class="login-options"><label><input id="loginRemember" type="checkbox"> 記住我的登入</label></div><p id="loginError" class="login-error" role="alert"></p><button id="loginSubmit" class="login-submit" type="submit">登入</button></form><div class="login-footer">帳號權限由群組管理員設定</div></section></main>`}
async function showLogin(){document.body.insertAdjacentHTML('beforeend',loginMarkup());const form=document.querySelector('#loginForm'),error=document.querySelector('#loginError'),submit=document.querySelector('#loginSubmit'),password=document.querySelector('#loginPassword');document.querySelector('#togglePassword').onclick=event=>{const show=password.type==='password';password.type=show?'text':'password';event.currentTarget.textContent=show?'隱藏':'顯示'};form.onsubmit=async event=>{event.preventDefault();error.textContent='';submit.disabled=true;submit.textContent='驗證中…';try{const auth=getAuth(),remember=document.querySelector('#loginRemember').checked;await setPersistence(auth,remember?browserLocalPersistence:browserSessionPersistence);const credential=await signInWithEmailAndPassword(auth,document.querySelector('#loginUsername').value.trim(),password.value);if(credential.user.uid!==ADMIN_UID){await signOut(auth);error.textContent='此帳號尚未取得工作區權限';return}const session={username:ADMIN_USERNAME,name:'系統管理員',groupId:'__admin__',groupName:'系統管理員',internal:true,superAdmin:true,allowedPages:[],loginAt:new Date().toISOString(),authUid:credential.user.uid};saveSession(session,remember);await recordAudit(session,'login');location.reload()}catch(err){console.error(err);error.textContent=['auth/invalid-credential','auth/wrong-password','auth/user-not-found'].includes(err.code)?'電子郵件或密碼錯誤':err.code==='auth/too-many-requests'?'登入嘗試過多，請稍後再試':'登入失敗：'+String(err.code||'連線異常')}finally{submit.disabled=false;submit.textContent='登入'}};requestAnimationFrame(()=>document.querySelector('#loginUsername')?.focus())}

const auth=getAuth(getApps().length?getApps()[0]:initializeApp(cfg));await auth.authStateReady();const user=auth.currentUser;const saved=readSession();const session=user?.uid===ADMIN_UID?{username:ADMIN_USERNAME,name:'系統管理員',groupId:'__admin__',groupName:'系統管理員',internal:true,superAdmin:true,allowedPages:[],loginAt:saved?.authUid===user.uid?saved.loginAt:new Date().toISOString(),authUid:user.uid}:null;if(session){document.documentElement.classList.add('is-authenticated','auth-ready');window.__omniplaySession=session;window.__omniplayCanEdit=true;installDownloadAudit(session);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>addLogout(session),{once:true});else addLogout(session)}else{if(user)await signOut(auth);for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}document.documentElement.classList.add('needs-login');await new Promise(resolve=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',resolve,{once:true});else resolve()});await showLogin();await new Promise(()=>{})}
