import { accessSession, BOOTSTRAP_UID, BOOTSTRAP_EMAIL } from './access-model.js?v=20261008-groups-1';
import { memberCredentials, ADMIN_UID, ADMIN_EMAIL, ADMIN_USERNAME } from './member-model.js?v=20261008-groups-1';
import{getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import{getFirestore,doc,getDoc,collection,addDoc,getDocs,query,orderBy,limit,serverTimestamp,setDoc,updateDoc,onSnapshot,where,writeBatch}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import{getAuth,signInWithEmailAndPassword,signOut,setPersistence,browserLocalPersistence,browserSessionPersistence}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
const cfg={apiKey:'AIzaSyB02CLJIYLJgQ2LkMVgYomObyl1kQC84eI',authDomain:'omniplay-op.firebaseapp.com',projectId:'omniplay-op',storageBucket:'omniplay-op.firebasestorage.app',messagingSenderId:'742295844045',appId:'1:742295844045:web:8399ae7bdb21c6a9d12584'};
const SESSION_KEY='omniplay-login-session-v1',CUSTOMER_KEY='omniplay-customer-session',ADMIN_KEY='omniplay-admin-session';
const LOGIN_USERNAME=ADMIN_EMAIL;
const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function passwordHash(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function workspaceRef(){const app=getApps().length?getApps()[0]:initializeApp(cfg),db=getFirestore(app);return doc(db,'omniplay','workspace')}
function auditRef(){const app=getApps().length?getApps()[0]:initializeApp(cfg);return collection(getFirestore(app),'omniplay-audit-events')}
function canViewAudit(session=window.__omniplaySession){return!!session&&(session.canEdit||(session.internal&&String(session.username||'').trim().toLowerCase()==='k'))}
async function recordAudit(account,action,item=''){try{await addDoc(auditRef(),{authUid:account.authUid||'',username:account.username||'',name:account.name||account.username||'',groupName:account.groupName||'',action,item:String(item||''),createdAt:serverTimestamp(),createdAtIso:new Date().toISOString()})}catch(error){console.warn('audit log',error)}}
function auditTime(value){const date=value?.toDate?.()||new Date(value||0);return Number.isNaN(date.getTime())?'—':date.toLocaleString('zh-TW',{hour12:false})}
async function showAuditLog(){let dialog=document.querySelector('#auditLogDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='auditLogDialog';dialog.style.cssText='width:min(900px,calc(100vw - 32px));max-height:82vh;border:1px solid #cbd5e1;border-radius:14px;padding:0;box-shadow:0 24px 70px rgba(15,23,42,.3)';dialog.innerHTML='<section style="padding:20px;background:#fff;color:#172033"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px"><div><h2 style="margin:0 0 4px">操作紀錄</h2><small style="color:#64748b">最多顯示最近 500 筆</small></div><div style="display:flex;gap:8px"><button type="button" id="auditExport" class="secondary">下載 CSV</button><button type="button" data-audit-close class="secondary">關閉</button></div></div><div id="auditLogBody" style="overflow:auto;max-height:62vh">載入中…</div></section>';document.body.append(dialog);dialog.querySelector('[data-audit-close]').onclick=()=>dialog.close()}const body=dialog.querySelector('#auditLogBody');body.textContent='載入中…';dialog.showModal();showActiveSessions(dialog);try{const snap=await getDocs(query(auditRef(),orderBy('createdAt','desc'),limit(500))),rows=snap.docs.map(item=>item.data()).filter(row=>!(row.action==='download' && String(row.item||'').includes('操作紀錄')));dialog._auditRows=rows;body.innerHTML=rows.length?'<table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr><th>時間</th><th>人員</th><th>帳號</th><th>群組</th><th>動作</th><th>項目</th></tr></thead><tbody>'+rows.map(row=>`<tr><td>${esc(auditTime(row.createdAt||row.createdAtIso))}</td><td>${esc(row.name||'—')}</td><td>${esc(row.username||'—')}</td><td>${esc(row.groupName||'—')}</td><td>${row.action==='login'?'登入':'下載'}</td><td>${esc(row.item||'—')}</td></tr>`).join('')+'</tbody></table>':'尚無紀錄';body.querySelectorAll('th,td').forEach(cell=>cell.style.cssText='padding:9px 10px;border-bottom:1px solid #e2e8f0;text-align:left;white-space:nowrap')}catch(error){console.error(error);body.textContent='紀錄載入失敗'}dialog.querySelector('#auditExport').onclick=()=>{const rows=dialog._auditRows||[],csv=[['時間','人員','帳號','群組','動作','項目'],...rows.map(row=>[auditTime(row.createdAt||row.createdAtIso),row.name,row.username,row.groupName,row.action==='login'?'登入':'下載',row.item])].map(cols=>cols.map(value=>'"'+String(value||'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`OMNIPLAY登入下載紀錄_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}}

const PRESENCE_KEY='omniplay-active-connection-v1';let presenceRef=null,presenceTimer=null,presenceUnsubscribe=null,presenceBusy=false;
async function startPresence(session){const db=getFirestore();let id=sessionStorage.getItem(PRESENCE_KEY);if(!id){id=crypto.randomUUID();sessionStorage.setItem(PRESENCE_KEY,id)}presenceRef=doc(db,'omniplay-active-sessions',id);try{const existing=await getDoc(presenceRef);if(existing.exists()&&existing.data().revoked){await logout();return}if(!existing.exists())await setDoc(presenceRef,{authUid:session.authUid,username:session.username,name:session.name||session.username,groupName:session.groupName||'',startedAt:serverTimestamp(),lastSeen:serverTimestamp(),active:true,revoked:false});else await updateDoc(presenceRef,{lastSeen:serverTimestamp(),active:true});
presenceUnsubscribe=onSnapshot(presenceRef,snap=>{if(snap.exists()&&snap.data().revoked){alert('管理者已將此帳號強制登出');logout()}},error=>console.warn('active connection listener',error));const heartbeat=async()=>{if(presenceBusy||!getAuth().currentUser)return;presenceBusy=true;try{await updateDoc(presenceRef,{lastSeen:serverTimestamp(),active:true})}catch(error){console.warn('connection heartbeat',error)}finally{presenceBusy=false}};presenceTimer=setInterval(heartbeat,30000);window.addEventListener('focus',heartbeat);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')heartbeat()});window.addEventListener('pagehide',()=>{updateDoc(presenceRef,{active:false,lastSeen:serverTimestamp()}).catch(()=>{})});}catch(error){window.__omniplayPresenceError='目前登入者功能尚未啟用，請先發布新版 Firestore 規則。';console.warn('active sessions',error)}}
async function showActiveSessions(dialog){let panel=dialog.querySelector('#activeSessionPanel');if(!panel){panel=document.createElement('section');panel.id='activeSessionPanel';panel.style.cssText='margin-bottom:20px;padding:14px;border:1px solid #d4e0ef;border-radius:10px;background:#f8fbff';(dialog.querySelector('#auditLogBody')||dialog.querySelector('#auditFilterBody')).before(panel)}panel.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><div><strong>目前登入者</strong><small style="display:block;color:#64748b">每 30 秒回報；列出最近 2 分鐘仍有回報的連線</small></div><button class="secondary" id="refreshActiveSessions">重新整理</button></div><div id="activeSessionRows" style="margin-top:12px">載入中…</div>';panel.querySelector('#refreshActiveSessions').onclick=()=>showActiveSessions(dialog);const body=panel.querySelector('#activeSessionRows');try{const snap=await getDocs(query(collection(getFirestore(),'omniplay-active-sessions'),where('lastSeen','>',new Date(Date.now()-120000)))),groups=new Map();for(const doc of snap.docs){const row=doc.data();if(!row.active||row.revoked)continue;const item=groups.get(row.authUid)||{...row,count:0};item.count++;if((row.lastSeen?.toMillis?.()||0)>(item.lastSeen?.toMillis?.()||0))item.lastSeen=row.lastSeen;groups.set(row.authUid,item)}const ownerConfig=await getDoc(doc(getFirestore(),'omniplay-security','access')),protectedUid=ownerConfig.exists()?ownerConfig.data().ownerUid:BOOTSTRAP_UID;const rows=[...groups.values()];body.innerHTML=rows.length?'<table style="width:100%;font-size:13px"><thead><tr><th>帳號</th><th>群組</th><th>連線數</th><th>最後回報</th><th>操作</th></tr></thead><tbody>'+rows.map(row=>`<tr><td>${esc(row.username)}</td><td>${esc(row.groupName)}</td><td>${row.count}</td><td>${esc(auditTime(row.lastSeen))}</td><td>${window.__omniplaySession?.canEdit&&row.authUid!==window.__omniplaySession.authUid&&row.authUid!==protectedUid?`<button class="secondary" data-force-logout="${esc(row.authUid)}" data-username="${esc(row.username)}">強制登出</button>`:'—'}</td></tr>`).join('')+'</tbody></table>':'目前沒有登入中的連線';body.querySelectorAll('td,th').forEach(cell=>cell.style.cssText='text-align:left;padding:8px;border-bottom:1px solid #e2e8f0');body.querySelectorAll('[data-force-logout]').forEach(button=>button.onclick=async()=>{if(!confirm('確定將「'+button.dataset.username+'」的所有網站連線登出？'))return;button.disabled=true;try{const snap=await getDocs(query(collection(getFirestore(),'omniplay-active-sessions'),where('authUid','==',button.dataset.forceLogout)));for(let i=0;i<snap.docs.length;i+=200){const batch=writeBatch(getFirestore());for(const row of snap.docs.slice(i,i+200))batch.update(row.ref,{revoked:true,active:false,kickedAt:serverTimestamp(),kickedBy:getAuth().currentUser.uid});await batch.commit()}await showActiveSessions(dialog)}catch(error){button.disabled=false;alert('強制登出失敗：'+(error.code||error.message))}})}catch(error){body.textContent=window.__omniplayPresenceError||'無法讀取目前登入者，請確認新版 Firestore 規則已發布。'}}

window.showOmniplayActiveSessions=showActiveSessions;
function installDownloadAudit(session){document.addEventListener('click',event=>{const target=event.target.closest?.('a[download],button,[role="button"]');if(!target||target.closest('#auditLogDialog,#auditFilterDialog')||target.closest('.audit-log-btn'))return;const label=(target.getAttribute('download')||target.title||target.getAttribute('aria-label')||target.textContent||'').trim();if(/下載|download/i.test(label))recordAudit(session,'download',label.slice(0,180))},true)}
function readSession(){for(const store of[localStorage,sessionStorage]){try{const value=JSON.parse(store.getItem(SESSION_KEY)||'null');if(value?.authUid)return value}catch{}}return null}
function saveSession(session,remember){for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}const store=remember?localStorage:sessionStorage;store.setItem(SESSION_KEY,JSON.stringify(session));if(session.internal)store.setItem(ADMIN_KEY,JSON.stringify(session));else store.setItem(CUSTOMER_KEY,JSON.stringify(session))}
async function logout(){clearInterval(presenceTimer);presenceUnsubscribe?.();if(presenceRef)try{const snap=await getDoc(presenceRef);if(snap.exists()&&!snap.data().revoked)await updateDoc(presenceRef,{active:false,lastSeen:serverTimestamp()})}catch{}sessionStorage.removeItem(PRESENCE_KEY);for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}await signOut(getAuth());location.reload()}
function addLogout(session){if(document.querySelector('.session-controls'))return;const controls=document.createElement('div');controls.className='session-controls';const name=document.createElement('span');name.className='login-user';name.textContent=session.name||session.username;const logoutButton=document.createElement('button');logoutButton.type='button';logoutButton.className='secondary logout-btn';logoutButton.textContent='登出';logoutButton.onclick=logout;controls.append(name);if(canViewAudit(session)){const auditButton=document.createElement('button');auditButton.type='button';auditButton.className='secondary audit-log-btn';auditButton.textContent='操作紀錄';auditButton.onclick=showAuditLog;controls.append(auditButton)}controls.append(logoutButton);const settings=document.createElement('details');settings.className='account-settings';const summary=document.createElement('summary');summary.textContent='⚙️';summary.title='帳號與管理設定';summary.setAttribute('aria-label','帳號與管理設定');const menu=document.createElement('div');menu.className='account-settings-menu';for(const button of [...controls.querySelectorAll('button')])menu.append(button);settings.append(summary,menu);controls.append(settings);menu.addEventListener('click',event=>{if(event.target.closest('button'))settings.open=false});document.addEventListener('click',event=>{if(!settings.contains(event.target))settings.open=false});settings.addEventListener('keydown',event=>{if(event.key==='Escape'){settings.open=false;summary.focus()}});(document.querySelector('.sidebar')||document.body).append(controls)}
function installReadOnlyMode(){window.__omniplayCanEdit=false;document.documentElement.classList.add('viewer-mode');const style=document.createElement('style');style.textContent='.viewer-mode .admin-only,.viewer-mode .platform-actions,.viewer-mode .group-manager-actions,.viewer-mode #addCategoryBtn,.viewer-mode #addPageBtn,.viewer-mode [data-edit-action]{display:none!important}.viewer-mode [contenteditable="true"]{cursor:default!important}.viewer-mode .sheet-workspace button:not(#glNativeSearch button){pointer-events:none!important;opacity:.55}.viewer-mode #glNativeSearch button{pointer-events:auto!important;opacity:1!important}';document.head.appendChild(style);const safe=target=>!!target?.closest?.('.session-controls,#glNativeSearch,#glSearch,#opGameSearch,[data-viewer-control]'),lockFields=()=>document.querySelectorAll('#workspace input,#workspace textarea,#workspace select,[contenteditable="true"]').forEach(el=>{if(safe(el))return;if(el.matches('[contenteditable]'))el.contentEditable='false';else el.disabled=true});new MutationObserver(lockFields).observe(document.documentElement,{childList:true,subtree:true});lockFields();for(const type of['beforeinput','paste','cut','drop'])document.addEventListener(type,e=>{if(!safe(e.target))e.preventDefault()},true);document.addEventListener('contextmenu',e=>{if(e.target.closest?.('#workspace')&&!safe(e.target)){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('keydown',e=>{if(safe(e.target))return;const sheet=e.target.closest?.('.sheet-workspace')||document.querySelector('.sheet-workspace:hover');if(!sheet)return;const blocked=e.key.length===1&&!e.ctrlKey&&!e.metaKey||['Backspace','Delete','Enter','F2'].includes(e.key)||(e.ctrlKey||e.metaKey)&&['v','x'].includes(e.key.toLowerCase());if(blocked){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('click',e=>{if(safe(e.target))return;const button=e.target.closest?.('button,[role="button"]');if(!button)return;const label=`${button.textContent||''} ${button.title||''} ${button.getAttribute('aria-label')||''}`;if(button.closest('.sheet-workspace')||/(新增|建立|編輯|修改|刪除|移除|儲存|上傳|設定權限)/.test(label)){e.preventDefault();e.stopImmediatePropagation()}},true)}
function loginMarkup(){return`<main class="login-screen"><section class="login-card"><div class="login-brand"><span>🔥</span><div><strong>OMNIPLAY ASSETS</strong><small>Game Information &amp; Marketing Resources</small></div></div><div class="login-heading"><h1>登入工作區</h1><p>請輸入帳號與密碼</p></div><form id="loginForm"><label>登入帳號<input id="loginUsername" autocomplete="username" required placeholder="請輸入登入帳號"></label><label>登入密碼<div class="login-password"><input id="loginPassword" type="password" autocomplete="current-password" required placeholder="請輸入密碼"><button type="button" id="togglePassword" aria-label="顯示密碼">顯示</button></div></label><div class="login-options"><label><input id="loginRemember" type="checkbox"> 記住我的登入</label></div><p id="loginError" class="login-error" role="alert"></p><button id="loginSubmit" class="login-submit" type="submit">登入</button></form><div class="login-footer">請使用人員管理中設定的帳號與密碼</div></section></main>`}
async function flushPendingLoginAudit(){
 let pending;try{pending=JSON.parse(sessionStorage.getItem('omniplay-pending-login-audit')||'null')}catch{return}
 if(!pending||pending.authUid!==getAuth().currentUser?.uid)return;
 try{await setDoc(doc(getFirestore(),'omniplay-audit-events',pending.id),{...pending.data,createdAt:serverTimestamp()});if(JSON.parse(sessionStorage.getItem('omniplay-pending-login-audit')||'null')?.id===pending.id)sessionStorage.removeItem('omniplay-pending-login-audit')}catch(error){console.warn('pending login audit',error)}
}
async function saveLoginAudit(session){
 const pending={id:crypto.randomUUID(),authUid:session.authUid,data:{authUid:session.authUid||'',username:session.username||'',name:session.name||session.username||'',groupName:session.groupName||'',action:'login',item:'',createdAtIso:new Date().toISOString()}};
 sessionStorage.setItem('omniplay-pending-login-audit',JSON.stringify(pending));
 await Promise.race([flushPendingLoginAudit(),new Promise(resolve=>setTimeout(resolve,1500))]);
}
async function showLogin(){document.body.insertAdjacentHTML('beforeend',loginMarkup());const form=document.querySelector('#loginForm'),error=document.querySelector('#loginError'),submit=document.querySelector('#loginSubmit'),password=document.querySelector('#loginPassword');document.querySelector('#togglePassword').onclick=event=>{const show=password.type==='password';password.type=show?'text':'password';event.currentTarget.textContent=show?'隱藏':'顯示'};form.onsubmit=async event=>{event.preventDefault();error.textContent='';submit.disabled=true;submit.textContent='驗證中…';try{const auth=getAuth(),remember=document.querySelector('#loginRemember').checked;await setPersistence(auth,remember?browserLocalPersistence:browserSessionPersistence);const username=document.querySelector('#loginUsername').value.trim();const administrator=ADMIN_EMAIL===username.toLowerCase();
let credential;
if(administrator){
 credential=await signInWithEmailAndPassword(auth,ADMIN_EMAIL,password.value);
}else{const bridge=await memberCredentials(username,password.value);credential=await signInWithEmailAndPassword(auth,bridge.email,bridge.password)}
const session=await resolveSession(credential.user);
if(!session){await signOut(auth);error.textContent='此帳號沒有工作區權限；若已完成交接，請使用 Rondo 登入';return}
sessionStorage.removeItem(PRESENCE_KEY);saveSession(session,remember);await saveLoginAudit(session);location.reload()}catch(err){console.error(err);error.textContent=['auth/invalid-credential','auth/wrong-password','auth/user-not-found'].includes(err.code)?'帳號或密碼錯誤':err.code==='auth/too-many-requests'?'登入嘗試過多，請稍後再試':err.code==='permission-denied'?'此帳號的群組權限尚未啟用，請聯絡管理員':'登入失敗：'+String(err.message||err.code||'連線異常')}finally{submit.disabled=false;submit.textContent='登入'}};requestAnimationFrame(()=>document.querySelector('#loginUsername')?.focus())}

async function resolveSession(user){
 if(!user)return null;
 const db=getFirestore();
 const [configResult,profileResult]=await Promise.allSettled([
  getDoc(doc(db,'omniplay-security','access')),
  user.uid===BOOTSTRAP_UID?Promise.resolve(null):getDoc(doc(db,'omniplay-member-access',user.uid))
 ]);
 let config=null,profile=null,view=null;
 if(configResult.status==='fulfilled'){const snap=configResult.value;if(snap.exists())config=snap.data()}
 else if(user.uid!==BOOTSTRAP_UID)throw new Error('請先發布新版 Firebase 規則，才能啟用人員登入');
 const ownerUid=config?.ownerUid||BOOTSTRAP_UID;
 if(user.uid===BOOTSTRAP_UID&&ownerUid!==BOOTSTRAP_UID)return null;
 if(profileResult.status==='rejected')throw profileResult.reason;
 if(profileResult.value?.exists())profile=profileResult.value.data();
 if(profile?.enabled&&user.uid!==ownerUid&&!(config?.credentialsMigrated&&['OMNIPLAY','OMNIPLAY Support'].includes(String(profile.groupName||'').trim()))){const snap=await getDoc(doc(db,'omniplay-group-views',profile.groupId));if(snap.exists())view=snap.data();}
 const session=accessSession(user,config,profile,view);
 if(session)session.loginAt=readSession()?.authUid===user.uid?readSession().loginAt:new Date().toISOString();
 return session;
}
function loginStep(promise,label,milliseconds=15000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(label+'連線逾時，請重新載入後再試')),milliseconds);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
const auth=getAuth(getApps().length?getApps().find(app=>app.name==='[DEFAULT]'):initializeApp(cfg));
await loginStep(auth.authStateReady(),'登入狀態檢查');
let session=null,accessError='';
try{session=await loginStep(resolveSession(auth.currentUser),'讀取帳號權限')}catch(error){accessError=error.code==='permission-denied'?'此帳號的群組權限尚未啟用，請聯絡管理員':String(error.message||'無法讀取人員權限，請稍後再試')}
if(session){ void flushPendingLoginAudit();
 void startPresence(session);
 document.documentElement.classList.add('is-authenticated','auth-ready');window.__omniplaySession=session;window.__omniplayCanEdit=!!session.canEdit;
 if(!session.canEdit)installReadOnlyMode();
 if(session.role==='admin'){document.documentElement.classList.add('regular-admin');const style=document.createElement('style');style.textContent='.regular-admin #groupManagerBtn,.regular-admin #addManagedGroup,.regular-admin .add-option[data-target="customerGroup"]{display:none!important}';document.head.append(style);}
 installDownloadAudit(session);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>addLogout(session),{once:true});else addLogout(session);
}else{
 if(auth.currentUser)await signOut(auth);
 for(const store of[localStorage,sessionStorage]){store.removeItem(SESSION_KEY);store.removeItem(CUSTOMER_KEY);store.removeItem(ADMIN_KEY)}
 document.documentElement.classList.add('needs-login');
 await new Promise(resolve=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',resolve,{once:true});else resolve()});
 await showLogin();if(accessError)document.querySelector('#loginError').textContent=accessError;await new Promise(()=>{});
}

